#!/bin/sh
#*****************************************************************************
#
#  This script is used to user objects 
#
#  USAGE: chkdblinks
#
#*****************************************************************************

echo "**************************************************************"
echo "Users with Default passwords for $ORACLE_SID "
echo "**************************************************************"

sqlplus -s "/ as sysdba" <<EOS
set pages 1000 lines 90 trimsp on feed off
col Status format a20
col username format a30
select username , account_status "Status"
 from dba_users
 where password in
('E066D214D5421CCC',  -- dbsnmp
 '24ABAB8B06281B4C',  -- ctxsys
 '72979A94BAD2AF80',  -- mdsys
 '9AAEB2214DCC9A31',  -- mdsys
 'C252E8FA117AF049',  -- odm
 'A7A32CD03D3CE8D5',  -- odm_mtr
 '88A2B2C183431F00',  -- ordplugins
 '7EFA02EC7EA6B86F',  -- ordsys
 '9B616F5489F90AD7',  -- ordcommon
 '4A3BA55E08595C81',  -- outln
 'F894844C34402B67',  -- scott
 '3F9FBD883D787341',  -- wk_proxy
 '79DF7A1BD138CF11',  -- wk_sys
 '7C9BA362F8314299',  -- wmsys
 '88D8364765FCE6AF',  -- xdb
 'F9DA8977092B7B81',  -- tracesvr
 '9300C0977D7DC75E',  -- oas_public
 'A97282CE3D94E29E',  -- websys
 'AC9700FD3F1410EB',  -- lbacsys
 'E7B5D92911C831E1',  -- rman
 'AC98877DE1297365',  -- perfstat
 '66F4EF5650C20355',  -- exfsys
 '84B8CBCA4D477FA3',  -- si_informtn_schema
 'D4C5016086B2DC6A',  -- sys
 '5638228DAF52805F',  -- sys
 'D4DF7931AB130E37')  -- system
 order by 1
;

EOS

echo ""
echo "**************************************************************"
echo "Users with same password for $ORACLE_SID "
echo "**************************************************************"
echo " set pages 0 lines 199 trimsp on feed off echo off
col username for a30            
select username from dba_users order by 1
/ " | sqlplus -s "/ as sysdba" |while read USERNAME
do
	echo "set pages 0 lines 199 trimsp on feed off echo off
	set echo off
	select 'not_ok' from dual;
/ " | sqlplus -s $USERNAME/$USERNAME | grep not_ok | wc -l | read result
	if (( $result>0 ))
	then
		echo "$USERNAME "
	fi
done
