#!/bin/sh
#*****************************************************************************
#
#  This script is used to copy sequences from staging area to prod area
#
#  USAGE: copy_seq_stage_to_prod username
#
#*****************************************************************************

typeset -u OWNER=$1

#----------------------------------------------------------------------#
# Checking the input params                                            #
#----------------------------------------------------------------------#
if [ ${#*} -lt 1 ]
then
    echo "Usage : <$prog_name> MASTER_USER   (i.e. BLREFWORK_MASTER -> BLREFWORK)"
    echo "Eample: <$prog_name> PD_WORK_MASTER"
    exit 1
fi

if [ `echo $OWNER | grep MASTER | wc -l` = 0 ]
then
        echo "OWNER Must have MASTER user"
        exit 1
fi

TEMP_FILE=/tmp/copy_seq_stage_to_prod_$$.sql
TEMP_FILE_LOG=/tmp/copy_seq_stage_to_prod_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 250 pages 0 echo off trimspo on
spool $TEMP_FILE

select 'DROP SEQUENCE '||replace(sequence_owner,'_MASTER','')||'.'||sequence_name ||';'||chr(10)||
       'CREATE SEQUENCE '||replace(sequence_owner,'_MASTER','')||'.'||sequence_name ||chr(10)||
       'START WITH '||last_number||chr(10)||'MAXVALUE '||max_value||chr(10)||
       'MINVALUE '||MIN_VALUE||chr(10)||decode(CYCLE_FLAG,'Y','CYCLE','NOCYCLE')||chr(10)||
       'CACHE '||cache_size||chr(10)||decode(ORDER_FLAG,'Y','ORDER','NOORDER')||';'
from dba_sequences
where sequence_owner = '$OWNER'
and sequence_name in (select sequence_name from dba_sequences where sequence_owner = replace(sequence_owner,'_MASTER',''));

select 'GRANT '||priv.privilege||' ON '||priv.owner||'.'||priv.table_name||' TO '||priv.grantee||';'
from dba_tab_privs priv,
     dba_sequences seq
     where priv.owner = replace('$OWNER','_MASTER','')
     and   priv.table_name=seq.sequence_name
     and   priv.owner=seq.sequence_owner;
       
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "CREATE SEQUENCE " $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes create sequence to execute "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
typeset -u PARAM=`echo $4|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
        echo "Would you like to execute ? (Y/N) \c"; read Local
fi

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
     	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors create sequence executed with errors "
	echo "------------------------------------------------------------------------------"
        grep ORA- $TEMP_FILE_LOG

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
