#!/bin/sh
#*****************************************************************************
#
#  This script is used to show all invalid objects and compile them 
#
#  USAGE: showcompile
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

export TEMP_FILE=/tmp/show_compile_$$.sql
export TEMP_FILE_LOG=/tmp/show_compile_log_$$.sql
echo "set termout off trimspo on lines 199 feed off pages 0 echo off
spool $TEMP_FILE
select 'alter index '||owner||'.'||index_name||' rebuild parallel 16 nologging;'||chr(10)||'alter index '||owner||'.'||index_name||' noparallel logging;' from dba_indexes di where not exists (select '' from dba_ind_partitions dip where dip.index_name=di.index_name and dip.index_owner=di.owner) and status != 'VALID';
select 'alter index '||index_owner||'.'||index_name||' rebuild partition '||partition_name||' parallel 16 ;'||chr(10)||'alter index '||index_owner||'.'||index_name||' noparallel logging;' from dba_ind_partitions where status not in ( 'USABLE','N/A');
select 'alter index '||owner||'.'||index_name||' rebuild parallel 16;' from dba_indexes where funcidx_status='DISABLED';
spool off
" | sqlplus -s "/ as sysdba" > /dev/null

#--------------------------------------------------------------------------------------------
head -n 10 $TEMP_FILE
echo "..."

num_of_changes=`grep -i "rebuild" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes indexes to rebuild "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi

typeset -u PARAM=`echo $1|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on time on timing on 
	spool $TEMP_FILE_LOG
        set term off
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "compilation err" $TEMP_FILE_LOG | wc -l`
	num_of_success=`grep -i "altered" $TEMP_FILE_LOG | grep -v "compilation err" | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_success objects compiled/rebuild successfully "
	echo "$num_of_errors objects altered with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
