#!/bin/ksh
#*****************************************************************************
#
#  This script is used to generate drop synonyms for user 
#
#  USAGE: gencreatesappynonym username
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "User must be provided: \c"; read NAME
fi

TEMP_FILE=/tmp/gencreatesynonym_$$.sql
TEMP_FILE_LOG=/tmp/gencreatesynonym_run_$$.sql

sqlplus -s "/ as sysdba" >/dev/null <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
set term off
spool $TEMP_FILE
select 'create or replace synonym $NAME.'||object_name||' for '||owner||'.'||object_name||';' 
from dba_objects 
where 
        object_type in ('TABLE','SEQUENCE','VIEW') 
        and owner not in ('REFREAD','PC_WORK')  and owner not like '%MASTER%' and owner not like '%TEMP_USER%'
        and (owner like '%WORK%' or owner like '%REF%') 
        and owner not like '%QUERY%'
        and owner not like 'SENSIS%'
        and object_name not like 'MLOG%'
        and object_name not like 'DR$%'
        and object_name not like 'RUPD%'
order by object_type,object_name;
spool off
EOF

#--------------------------------------------------------------------------------------------
head -n 10 $TEMP_FILE
echo "..."

num_of_changes=`grep -i "SYNON" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes synonyms to create "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
typeset -u PARAM=`echo $3|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi
	
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
        set term off
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | grep -v 00955 | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors synonyms created with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
