#!/bin/ksh
#*****************************************************************************
#
#  This script is used to generate truncate for user 
#
#  USAGE: gencreate_dev_user username
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

sqlplus "/ as sysdba" <<EOF
set line 132 pages 0 echo on trimspo on
CREATE USER DBA_OPER
  IDENTIFIED BY VALUES '2A06F8DF62B70091'
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  GRANT CONNECT TO DBA_OPER;
  ALTER USER DBA_OPER DEFAULT ROLE ALL;

  GRANT SELECT ON SYS.V_\$LOGSTDBY_PROGRESS TO DBA_OPER;
  GRANT SELECT ON SYS.V_\$LOGSTDBY_STATE TO DBA_OPER;
EOF
add_to_alt_user_password.sh DBA_OPER
