#!/bin/sh
#*****************************************************************************
#
#  This script is used to generate drop synonyms for user 
#
#  USAGE: gencreatepubsynonym synonym_user
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

typeset -u SYN_OWNER=`echo $1|cut -d. -f1`
if [ -z "$SYN_OWNER" ] 
then
  echo "Synonym Owner must be provided: \c"; read SYN_OWNER
fi

TEMP_FILE=/tmp/gencreatepubsynonym_$$.sql
TEMP_FILE_LOG=/tmp/gencreatepubsynonym_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'create public synonym '||TABLE_NAME||' FOR '||owner||'.'||TABLE_NAME||';'
from dba_tables where owner='$SYN_OWNER'
union all
select 'create public synonym '||SEQUENCE_NAME||' FOR '||sequence_owner||'.'||SEQUENCE_NAME||';'
from dba_sequences where sequence_owner='$SYN_OWNER'
union all
select 'create public synonym '||view_NAME||' FOR '||owner||'.'||VIEW_NAME||';'
from dba_views where owner='$SYN_OWNER';
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "SYNON" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes public synonyms to create "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors public synonyms created with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
