#!/bin/sh
#*****************************************************************************
#
#  This script is used to generate drop synonyms for user 
#
#  USAGE: gencreatesynonym username synonym_user
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
typeset -u SYN_OWNER=`echo $2|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "User must be provided: \c"; read NAME
fi

if [ -z "$SYN_OWNER" ] 
then
  echo "Synonym Owner must be provided: \c"; read SYN_OWNER
fi

TEMP_FILE=/tmp/gencreatesynonym_$$.sql
TEMP_FILE_LOG=/tmp/gencreatesynonym_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'create synonym ${NAME}.'||TABLE_NAME||' FOR '||owner||'.'||TABLE_NAME||';'
from dba_tables where owner='$SYN_OWNER' and table_name not like 'MLOG%' and table_name not like 'RUPD%'
union all
select 'create synonym ${NAME}.'||view_NAME||' FOR '||owner||'.'||VIEW_NAME||';'
from dba_views where owner='$SYN_OWNER' and view_NAME not like 'MLOG%' and view_NAME not like 'RUPD%';
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "SYNON" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes synonyms to create "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
typeset -u PARAM=`echo $3|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi
	
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors synonyms created with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
