#!/bin/sh
#*****************************************************************************
#
#  This script is used to generate drop synonyms for user 
#
#  USAGE: gendropsynonym username pointing_owner
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "User must be provided: \c"; read NAME
fi

typeset -u SYNONYM_OWNER=`echo $2|cut -d. -f1`
if [ -z "$SYNONYM_OWNER" ] 
then
  echo "Pointing Owner must be provided: \c"; read SYNONYM_OWNER
fi

TEMP_FILE=/tmp/gendropsynonym_$$.sql
TEMP_FILE_LOG=/tmp/gendropsynonym_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'drop synonym '||OWNER||'.'||SYNONYM_NAME||';'
from dba_synonyms where owner='$NAME' and table_owner='$SYNONYM_OWNER';
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "SYNON" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes synonyms to drop "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors synonyms dropped with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
