#!/bin/ksh
#*****************************************************************************
#
#  This script is used to generate drop indexes for user
#
#  USAGE: gendropstandbyindex username
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************
TEMP_FILE=/tmp/gentriggerateuser_$$.sql
TEMP_FILE_LOG=/tmp/gentriggerateuser_run_$$.sql
HOST=`hostname`

if echo $HOST | egrep -q "28"
then
        echo "Running on $HOST"
else
        echo "this script should run only on the standby machine - supr28 or suut28"
        exit
fi

echo "
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'drop trigger '||owner||'.'||trigger_name||';'  
from dba_triggers
where 
    owner in ('REFWORK','REF_APPL','AUTHWORK')
    and trigger_name like '%_TR'
order by 1;
" | sqlplus -s "/ as sysdba" > /dev/null

#--------------------------------------------------------------------------------------------
head -n 10 $TEMP_FILE
echo "..."

num_of_changes=`egrep "alter|drop" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes objects to drop "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
typeset -u PARAM=`echo $1|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
        set term off
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors dropped with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
