#!/bin/sh
#*****************************************************************************
#
#  This script is used to show all invalid objects and compile them 
#
#  USAGE: gendropdir
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

export TEMP_FILE=/tmp/gen_drop_dir_$$.sql
export TEMP_FILE_LOG=/tmp/gen_drop_dir_log_$$.sql
echo "set termout off trimspo on lines 199 feed off pages 0 echo off
spool $TEMP_FILE
select 'drop directory '||directory_name||';' from dba_directories
where directory_name not in ('DATA_PUMP_DIR','ORACLE_OCM_CONFIG_DIR') and
directory_name not like 'QUEST%';
spool off
" | sqlplus -s "/ as sysdba" 
num_of_comp=`grep -i "drop" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_comp directories to drop "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_comp==0))
then
	rm -f $TEMP_FILE
	exit 0
fi

typeset -u PARAM=`echo $1|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_success=`grep -i "dropped" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_success directories dropped  successfully "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
