#!/bin/ksh
#*****************************************************************************
#
#  This script is used to generate truncate for user 
#
#  USAGE: gendropmlog username
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************
typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "User must be provided: \c"; read NAME
fi

TEMP_FILE=/tmp/gentruncateuser_$$.sql
TEMP_FILE_LOG=/tmp/gentruncateuser_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select distinct 'drop snapshot log on '||log_owner||'.'||master||' ;' from dba_snapshot_logs where log_owner='$NAME';
select distinct 'drop table '||owner||'.'||table_name||' ;' from dba_tables where table_name like 'MLOG\$_%' and owner='$NAME';
select distinct 'drop table '||owner||'.'||table_name||' ;' from dba_tables where table_name like 'RUPD\$_%' and owner='$NAME';
select distinct 'drop view '||owner||'.'||view_name||' ;' from dba_views where view_name like 'RUPD\$_%' and owner='$NAME';
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "drop" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes objects to drop "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors objects dropped with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
