#!/bin/ksh
#*****************************************************************************
#
#  This script is used to generate kill user 
#
#  USAGE: genkillsession username
#
#  By Adi Zohar - Sep 2004
#*****************************************************************************

. /oravl01/oracle/.profile >/dev/null

TEMP_FILE=/tmp/genkillolsm_$$.sh 
TEMP_FILE_LOG=/tmp/genkillolsm_run_$$.sql

sqlplus -s "/ as sysdba" <<-EOSQL
set feed off tab off
col sid for 99999
col serial# for 99999
col username for a22 head "Oracle User"
col osuser for a14 trunc
col machine for a30
col status for a5 trunc
col program for a25 trunc
alter session set nls_date_format = 'dd-MON:hh24:mi:ss';
set feed off pages 80 lines 200
select
        SID,
        sess.SERIAL#,
        sess.USERNAME,
        STATUS,
        OSUSER,
        PROCESS,
        MACHINE,
        LOGON_TIME, 
        sess.program,
        proc.spid
from 
    v\$session sess,
    v\$process proc
where
     (sess.program like '%olsm%ONLINE%')
     and status='ACTIVE'
     and sess.paddr=proc.addr (+);
quit
EOSQL
sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'kill -9 ' || proc.spid
from
    v\$session sess,
    v\$process proc
where
     (sess.program like '%olsm%ONLINE%')
     and status='ACTIVE'
     and sess.paddr=proc.addr (+);
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "kill" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes sessions to kill "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
Local=$1
if [ -z "$Local" ] 
then
        echo "Would you like to execute ? (Y/N) \c"; read Local
fi

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
        sh $TEMP_FILE
fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
