#!/bin/sh
#*****************************************************************************
#
#  This script is used to move table to another tablespace 8.1.7 
#
#  USAGE: genmove_object owner object_name dest_tablespace_name [ext_size]
#
#  By Adi Zohar - March 2003
#*****************************************************************************

typeset -u OWNER=`echo $1|cut -d. -f1`
if [ -z "$OWNER" ] 
then
  echo "Owner must be provided: \c"; read OWNER
fi

typeset -u NAME=`echo $2|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Object must be provided: \c"; read NAME
fi


typeset -u DESTNAME=`echo $3|cut -d. -f1`
if [ -z "$DESTNAME" ] 
then
  echo "Dest tablsapce must be provided: \c"; read DESTNAME
fi

typeset -u EXTSIZE=`echo $4|cut -d. -f1`

if [ ! -z "$EXTSIZE" ] 
then
  EXTSIZE_PREP="storage (initial $EXTSIZE next $EXTSIZE )"
else
  echo "set pages 0 lines 199 echo off verify off feedb off
  select trunc(next_extent/1024)||'K' from dba_tablespaces where tablespace_name='${DESTNAME}' and allocation_type='UNIFORM';
  " | sqlplus -s "/ as sysdba" | read EXT_DEST_TABLESPACE
	if [ ! -z "$EXT_DEST_TABLESPACE" ] 
	then
		echo "$DESTNAME is uniform $EXT_DEST_TABLESPACE extent"
		EXTSIZE_PREP="storage (initial $EXT_DEST_TABLESPACE next $EXT_DEST_TABLESPACE ) "
	fi
fi

TEMP_FILE=/tmp/genmove_object_tbsp_$$.sql
TEMP_FILE_LOG=/tmp/genmove_object_tbsp_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select /*+ ordered */ 'alter table '||ds.owner||'.'||table_name||' move lob('||column_name||') store as lobsegment (tablespace $DESTNAME );' 
	from  dba_lobs dl, dba_segments ds
	where ds.segment_name=dl.segment_name and ds.owner=dl.owner and ds.segment_name='${NAME}' and dl.owner='${OWNER}'
union all
select /*+ ordered */ 'alter table '||ds.owner||'.'||table_name||' move lob('||column_name||') store as lobsegment (tablespace $DESTNAME );'
from  dba_lobs dl, dba_segments ds
where ds.segment_name=dl.index_name and ds.owner=dl.owner and ds.segment_name='${NAME}' and dl.owner='${OWNER}'
union all
select 'alter table '||TABLE_OWNER||'.'||table_name||' move partition '||partition_name||' tablespace ${DESTNAME} $EXTSIZE_PREP nologging ;' 
	from dba_tab_partitions where partition_name='${NAME}' and table_owner='${OWNER}'
union all
select 'alter table '||TABLE_OWNER||'.'||table_name||' logging noparallel ;' 
	from dba_tab_partitions where partition_name='${NAME}' and table_owner='${OWNER}'
union all
select 'alter index '||INDEX_OWNER||'.'||index_name||' rebuild partition '||partition_name||' tablespace ${DESTNAME} $EXTSIZE_PREP nologging;' 
	from dba_ind_partitions where partition_name='${NAME}' and index_owner='${OWNER}'
union all
select 'alter index '||INDEX_OWNER||'.'||index_name||' logging noparallel  ;' 
	from dba_ind_partitions where partition_name='${NAME}' and index_owner='${OWNER}'
union all
select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' move tablespace $DESTNAME $EXTSIZE_PREP nologging;'
	from dba_tables dt where table_name ='${NAME}' and 
	not exists (select '' from dba_tab_partitions dtp where dt.table_name=dtp.table_name and dt.owner=dtp.table_owner)
union all
select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' logging noparallel  ;'
	from dba_tables dt where table_name ='${NAME}' and 
	not exists (select '' from dba_tab_partitions dtp where dt.table_name=dtp.table_name and dt.owner=dtp.table_owner)
union all
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' rebuild tablespace $DESTNAME $EXTSIZE_PREP nologging;'
	from dba_indexes dt where index_name = '${NAME}' and
	not exists (select '' from dba_ind_partitions dtp where dt.index_name=dtp.index_name and dt.owner=dtp.index_owner)
union all
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' logging noparallel ;'
	from dba_indexes dt where index_name = '${NAME}' and
	not exists (select '' from dba_ind_partitions dtp where dt.index_name=dtp.index_name and dt.owner=dtp.index_owner)
/
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "ALTER" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes table/index to rebuild "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	alter session set sort_area_size=29999999;
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors table/index to rebuilded with errors "
	echo "------------------------------------------------------------------------------"
	echo "Don't forget to run showcompile"
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
