#!/bin/sh
#*****************************************************************************
#
#  This script is used to move table to another tablespace 8.1.7 
#
#  USAGE: gentab_move_tbsp Tablespace_name DEST_TABLESPACE_NAME [extent_size]
#
#  By Adi Zohar - March 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Tablsapce must be provided: \c"; read NAME
fi

typeset -u DESTNAME=`echo $2|cut -d. -f1`
if [ -z "$DESTNAME" ] 
then
  echo "Dest tablsapce must be provided: \c"; read DESTNAME
fi

typeset -u EXTSIZE=`echo $3|cut -d. -f1`

if [ ! -z "$EXTSIZE" ] 
then
  EXTSIZE_PREP="storage (initial $EXTSIZE next $EXTSIZE )"
fi

TEMP_FILE=/tmp/gentab_move_tbsp_$$.sql
TEMP_FILE_LOG=/tmp/gentab_move_tbsp_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select /*+ ordered */ 'alter table '||ds.owner||'.'||table_name||' move lob('||column_name||') store as lobsegment (tablespace $DESTNAME );' 
	from  dba_lobs dl, dba_segments ds
	where ds.segment_name=dl.segment_name and ds.owner=dl.owner and ds.tablespace_name='${NAME}' and dl.owner<>'SYS'
union all
select /*+ ordered */ 'alter table '||ds.owner||'.'||table_name||' move lob('||column_name||') store as lobsegment (tablespace $DESTNAME );'
from  dba_lobs dl, dba_segments ds
where ds.segment_name=dl.index_name and ds.owner=dl.owner and ds.tablespace_name='${NAME}' and dl.owner<>'SYS'
union all
select 'alter table '||TABLE_OWNER||'.'||table_name||' move partition '||partition_name||' tablespace ${DESTNAME} $EXTSIZE_PREP ;' 
	from dba_tab_partitions where tablespace_name='${NAME}'
union all
select 'alter index '||INDEX_OWNER||'.'||index_name||' rebuild partition '||partition_name||' tablespace ${DESTNAME} $EXTSIZE_PREP ;' 
	from dba_ind_partitions where tablespace_name='${NAME}'
union all
select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' move tablespace $DESTNAME $EXTSIZE_PREP ;'
	from dba_tables dt where tablespace_name ='${NAME}' and 
	not exists (select '' from dba_tab_partitions dtp where dt.table_name=dtp.table_name and dt.owner=dtp.table_owner)
union all
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' rebuild tablespace $DESTNAME $EXTSIZE_PREP ;'
	from dba_indexes dt where tablespace_name = '${NAME}' and
	not exists (select '' from dba_ind_partitions dtp where dt.index_name=dtp.index_name and dt.owner=dtp.index_owner)
/
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "ALTER" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes table/index to rebuild "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	alter session set sort_area_size=9999999;
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors table/index to rebuilded with errors "
	echo "------------------------------------------------------------------------------"
	echo "Don't forget to run showcompile"
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
