#!/bin/sh
#*****************************************************************************
#
#  This script is used to move table to another tablespace 8.1.7 
#
#  USAGE: gentab_move_tbsp_size Tablespace_name DEST_TABLESPACE_NAME extent_size
#
#  By Adi Zohar - March 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Tablsapce must be provided: \c"; read NAME
fi

typeset -u DESTNAME=`echo $2|cut -d. -f1`
if [ -z "$DESTNAME" ] 
then
  echo "Dest tablsapce must be provided: \c"; read DESTNAME
fi

typeset -u EXTSIZE=`echo $3|cut -d. -f1`
if [ -z "$EXTSIZE" ] 
then
  echo "Extent Size must be provided: \c"; read EXTSIZE
fi

TEMP_FILE=/tmp/gentab_move_tbsp_$$.sql
TEMP_FILE_LOG=/tmp/gentab_move_tbsp_run_$$.sql

sqlplus -s / <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select /*+ ordered */ 'alter table '||ds.owner||'.'||table_name||' move lob('||column_name||') store as lobsegment (tablespace $DESTNAME );' from 
dba_lobs dl, dba_segments ds
where ds.segment_name=dl.segment_name and ds.owner=dl.owner and ds.tablespace_name='${NAME}' and dl.owner<>'SYS'
union all
select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' move tablespace $DESTNAME storage (initial $EXTSIZE next $EXTSIZE );'
	from dba_tables where tablespace_name ='${NAME}' 
union all
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' rebuild tablespace $DESTNAME  storage (initial $EXTSIZE next $EXTSIZE );'
	from dba_indexes where tablespace_name = '${NAME}' 
/
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "ALTER" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes table/index to rebuild "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	alter session set sort_area_size=9999999;
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus / 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors table/index to rebuilded with errors "
	echo "------------------------------------------------------------------------------"
	echo "Don't forget to run showcompile"
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
