#!/bin/sh
#*****************************************************************************
#
#  This script is used to generate to change the initial to be equal to next for 8.1.7 
#
#  USAGE: gentab_iniequnext_ext Tablespace_name
#
#  By Adi Zohar - March 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Tablsapce must be provided: \c"; read NAME
fi

TEMP_FILE=/tmp/gentab_iniequnext_ext_$$.sql
TEMP_FILE_LOG=/tmp/gentab_iniequnext_ext_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' move storage (initial '||next_extent||' );'
	from dba_tables where initial_extent<>next_extent and tablespace_name like '${NAME}%' and owner not in ('SYS','SYSTEM')
union all
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' rebuild storage (initial '||next_extent||' );'
	from dba_indexes where initial_extent<>next_extent and tablespace_name like '${NAME}%' and owner not in ('SYS','SYSTEM')
/
spool off
EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "ALTER" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes table/index to rebuild "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
echo "Would you like to execute ? (Y/N) \c"; read Local
if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	alter session set sort_area_size=9999999;
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors table/index to rebuilded with errors "
	echo "------------------------------------------------------------------------------"
	echo "Don't forget to run showcompile"
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
