#!/bin/sh
#*****************************************************************************
#
#  This script is used to generate truncate for user 
#
#  USAGE: gensnap username
#
#  By Adi Zohar 
#*****************************************************************************

typeset -u SITE_NAME=`echo $1|cut -d. -f1 | tr -A [a-z] [A-Z]`
if [ -z "$SITE_NAME" ] 
then
  echo "Site to Unregister \c"; read SITE_NAME
fi


TEMP_FILE=/tmp/genunregister_snapshot_$$.sql
TEMP_FILE_LOG=/tmp/genunregister_snapshot_run_$$.sql

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off verify off line 132 pages 0 echo off trimspo on
spool $TEMP_FILE
PROMPT
PROMPT 
select 'exec dbms_snapshot.unregister_snapshot('''||owner||''','''||name||''','''||snapshot_site||''');' from dba_registered_snapshots where snapshot_site like '%$SITE_NAME%';

EOF

#--------------------------------------------------------------------------------------------
num_of_changes=`grep -i "exec" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_changes snapshots to unregister "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if (( num_of_changes==0 ))
then
	rm -f $TEMP_FILE
	exit 0
fi
#--------------------------------------------------------------------------------------------
typeset -u PARAM=`echo $2|cut -d. -f1`
Local=$PARAM
if [ -z "$PARAM" ]
then
	echo "Would you like to execute ? (Y/N) \c"; read Local
fi

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
	echo "set echo on pages 0 lines 199 trimspo on
	spool $TEMP_FILE_LOG
	@$TEMP_FILE
	spool off
	" | sqlplus "/ as sysdba" 
	num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | grep -v "12003" | grep -v "01432" | wc -l`
	echo "------------------------------------------------------------------------------"
	echo "$num_of_errors snapshots unregistered  with errors "
	echo "------------------------------------------------------------------------------"

fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG
