#!/bin/sh
#*****************************************************************************
#
#  This script is used to show rollback segments status
#
#  USAGE: showobj_last_analyze
#
#  By Barbara Rabinowicz Jun 2005
#*****************************************************************************
typeset -u DAYS=`echo $1|cut -d. -f1`
if [ -z "$DAYS" ]
then
  echo "Number of days for last days must be provided: \c"; read DAYS
fi

TEMP_FILE=/tmp/analyze_objects_$$.sql
TEMP_FILE_LOG=/tmp/analyze_objects_$$.log
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG

sqlplus -s '/ as sysdba' <<EOF
set linesize 170 pages 100 feedback off trims on
col object_type format a12
SELECT 'TABLE' object_type,owner,table_name,TO_CHAR(last_analyzed,'YYYY/MM/DD HH24:MI') last_analyzed
FROM   dba_tables
WHERE (num_rows is null
   OR  last_analyzed < sysdate - $DAYS) 
  AND  owner not in ('SYS','SYSTEM','PRECISE_OI3')
UNION
SELECT 'INDEX' object_type,owner,index_name,TO_CHAR(last_analyzed,'YYYY/MM/DD HH24:MI') last_analyzed
FROM   dba_indexes
WHERE (num_rows is null
   OR  last_analyzed < sysdate - $DAYS)
  AND  owner not in ('SYS','SYSTEM','PRECISE_OI3')
;
prompt ====================== 
prompt Objects to be analyzed
prompt ======================

set pages 0 lines 200
spool /tmp/analyze_objects_$$.sql
SELECT 'EXEC DBMS_STATS.GATHER_TABLE_STATS(''' || owner || ''',''' || table_name || ''',null,20,false,''FOR ALL COLUMNS SIZE 1'',4,''DEFAULT'',TRUE,NULL,NULL,NULL);'
FROM   dba_tables
WHERE (num_rows is null
   OR  last_analyzed < sysdate - $DAYS) 
  AND  owner not in ('SYS','SYSTEM','PRECISE_OI3')
UNION
SELECT 'EXEC DBMS_STATS.GATHER_INDEX_STATS(''' || owner || ''',''' || index_name || ''',null,20);'
FROM   dba_indexes
WHERE (num_rows is null
   OR  last_analyzed < sysdate - $DAYS)
  AND  owner not in ('SYS','SYSTEM','PRECISE_OI3')
;
spool off
EOF

num_of_anal=`grep -i "exec" $TEMP_FILE | wc -l`
echo "------------------------------------------------------------------------------"
echo "$num_of_anal objects to analyze "
echo "Temporary script: $TEMP_FILE"
echo "------------------------------------------------------------------------------"
if [ $num_of_anal -eq 0 ]  
then
   rm -f $TEMP_FILE
   exit 0
fi

echo "Would you like to execute ? (Y/N)"
read Local

if [ "$Local" = "Y" -o "$Local" = "y" ]
then
        echo "set echo on pages 0 lines 199 trimspo on
        spool $TEMP_FILE_LOG
        @$TEMP_FILE
        spool off
        " | sqlplus "/ as sysdba"
        num_of_errors=`grep -i "ORA-" $TEMP_FILE_LOG | wc -l`
        num_of_success=`grep -i "successfully" $TEMP_FILE_LOG | wc -l`
        echo "------------------------------------------------------------------------------"
        echo "$num_of_success objects analyzed successfully "
        echo "$num_of_errors objects analyzed with errors "
        echo "------------------------------------------------------------------------------"
fi
rm -f $TEMP_FILE
rm -f $TEMP_FILE_LOG

