#!/bin/sh
#*****************************************************************************
#
#  This script is used to show all instances
#
#  USAGE: showdblinks
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

cat /etc/oratab |grep -i ":Y"
