#!/bin/sh
#*****************************************************************************
#
#  This script is used to show all roles
#
#  USAGE: showipcs
#
#  By Adi Zohar - Jun 2007 
#*****************************************************************************
ipcs -mob |egrep "oracle|ID"
echo "--------------------------------------------------------------------------"
ipcs -mob | grep oracle | awk '{print $8}' | awk '{ s += $1/1024/1024 } END {printf("Total (Gb): %10d\n",s)}'
