#!/bin/ksh
############################################3
# show8locks
# 
# by Adi Zohar
# 
# 01/02/2003
############################################3

sqlplus -s "/ as sysdba" <<EOF
col name for a35 head "LOCKED OBJECT" 
col status  for a3 head STA trunc
col inst_id for 9 head "INS"
col process for a6 head "OS PROC" trunc
col session_id for 99999 head SID 
col serial# for 999999 
col os_user_name for a10 head "OS USER"  trunc
col oracle_username for a13 head "LOCKING USER" trunc
col username for a11 trunc
col program for a40 trunc
col load_time for a14 trunc
col lock_held for a10 trunc
col shadow format a6
col object_name for a26 trunc
set feed off
alter session set NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI';
set feed on 

set pages 200
set lines 199

prompt ========================
prompt ==    Current Locks   ==
prompt ========================

--select a.session_id,b.serial#,b.status,a.oracle_username,a.os_user_name,a.process,c.name
--from sys.obj\$ c,v\$session b,v\$locked_object a
--where a.session_id=b.sid and c.obj#=a.object_id;

select /*+ ordered use_nl(a,b) */ 
    distinct inst_id,session_id,serial#,a.status,oracle_username,os_user_name,process, shadow, nvl(b.name,'-') object_name, lock_held, load_time, program
from
    (
    SELECT /*+ ordered use_hash(x,l,s,b,p) */ 
        x.inst_id,
        s.indx session_id,
        s.ksuseser serial#,
        DECODE (BITAND (s.ksuseidl, 11),1, 'ACTIVE',0, DECODE (BITAND (s.ksuseflg, 4096), 0, 'INACTIVE', 'CACHED'),2, 'SNIPED',3, 'SNIPED','KILLED') STATUS,
        s.ksuudlna oracle_username,
        s.ksuseunm os_user_name,
        p.ksuprpid shadow,
        decode(l.ksqlkmod,
   0, 'None',           /* Mon Lock equivalent */
   1, 'Null',           /* N */
   2, 'Row-S (SS)',     /* L */
   3, 'Row-X (SX)',     /* R */
   4, 'Share',          /* S */
   5, 'S/Row-X (SSX)',  /* C */
   6, 'Exclusive',      /* X */
   to_char(l.ksqlkmod)) lock_held,  
        x.ktcxbstm load_time, 
        s.ksusepid process,
        s.ksusepnm program,
        l.ktadmtab as obj#
    FROM 
        x\$ktcxb x, 
        x\$ksuse s, 
        x\$ktadm l,
        x\$ksupr p
    WHERE 
        x.ktcxbses = s.addr AND
        s.ksspaown= p.addr (+) AND
        x.ktcxbxba = l.kssobown (+) and 
        (
            l.ktadmtab is not null
            or
            l.ktadmtab is null and BITAND (x.ksspaflg, 1) != 0 AND BITAND (x.ktcxbflg, 2) != 0
            )
    ) a,
    sys.obj$ b
    where a.obj#=b.obj# (+)
        order by 11,1,2;

prompt ========================
prompt == Current Lock Waits ==
prompt ========================

set lines 200 head off verif off feed off
alter session set "_hash_join_enabled"=true;
set serveroutput on size 1000000
set feed on

exec sys.show_lock_pkg.showlock
exit
/
EOF
