#!/bin/sh
#*****************************************************************************
#
#  This script is used to show all dblinks
#
#  USAGE: showdblinks
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

sqlplus -s "/ as sysdba" <<EOF
set pages 100 lines 160 trimsp on
col DB_LINK format a30 heading "Link Name"
col OWNER format a25 heading "Owned by ..."
col USERNAME format a25 heading "Connect to..."
col HOST format a50 heading "Located in ..." 

select replace(DB_LINK,'.WORLD','') AS DB_LINK,OWNER,USERNAME,HOST
  from dba_db_links;
EOF
