#!/bin/sh
#*****************************************************************************
#
#  This script is used count number of free extents on the request size
#
#  USAGE: showfree extent_size (in megs)
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Extent size must be provided: (in megs) \c"; read NAME
fi

sqlplus -s "/ as sysdba" <<EOF
clear buffer
set feed off
set verify off
set line 132
set pages 200

column maxext format 999,999,999 head "Max Ext Size (MB)"
column num format 999,999 head "# of ${NAME}M"
column tablespace_name for a30
select tablespace_name, sum(floor(bytes/1024/1024/$NAME)) num , max(bytes/1024/1024) MAXEXT
		   from dba_free_space 
		   where bytes >= 1024*1024*$NAME and
		   tablespace_name not in ('SYSTEM','RBS')
group by tablespace_name 
ORDER BY 1,2
/
EOF
