#!/bin/ksh 
echo "set pages 1000 lines 132 feedback off
col DEFAULT_TABLESPACE head 'Default TBS' for a15 trunc
col TEMPORARY_TABLESPACE head 'TEMP TBS' for a15 trunc
col MB head 'Size (Mb)' for 9,999,999
col ACCOUNT_STATUS for a20 head Locked
col DBA for a4 
col CAT_ROLE for a8
col account_status for a15 head STATUS

break on report
compute sum of MB on report

select
                USERNAME,
                DEFAULT_TABLESPACE,
                TEMPORARY_TABLESPACE,
                CREATED,
                sum(nvl(blocks*8192/1024/1024,0)) MB,
                rl.granted_role as dba,
                decode(rlany.granted_role,'SELECT_CATALOG_ROLE','CAT_ROLE','') as CAT_ROLE,
                decode(account_status,'OPEN','',account_status) account_status
from 
    sys.seg$ seg, 
    dba_users du,
    (select grantee, granted_role from dba_role_privs where granted_role = upper('DBA')) rl,
    (select grantee, granted_role from dba_role_privs where granted_role = upper('SELECT_CATALOG_ROLE')) rlany
where
    seg.user# (+)= du.user_id and
    rl.GRANTEE (+)=du.username and
    rlany.GRANTEE (+)=du.username
group by username,   DEFAULT_TABLESPACE,  TEMPORARY_TABLESPACE, CREATED, rl.granted_role,rlany.granted_role     ,account_status
order by username;
" | sqlplus -s "/ as sysdba "


