#!/bin/sh
############################################3
# showspctsps
# 
# by Adi Zohar & Barbara
# 
# 01/08/2003
############################################3

typeset -u NAME=`echo $1|cut -d. -f1`
if [ -z "$NAME" ] 
then
  echo "Table Name be provided: \c"; read NAME
fi

sqlplus -s "/ as sysdba" <<EOF
set pages 0 lines 199 trimsp on echo off feed off
SET SERVEROUTPUT ON size 1000000 
DECLARE
    v_segment_owner              varchar2(255);
    v_segment_name               varchar2(255);
    v_segment_type               varchar2(255);
    v_total_blocks               number; 
    v_total_bytes                number;
    v_unused_blocks              number;
    v_unused_bytes               number;
    v_last_used_extent_file_id   number;
    v_last_used_extent_block_id  number;
    v_last_used_block            number;
    v_partition_name             varchar(255);
    cursor obj_cur is
       select owner
		,segment_name
		,segment_type
		,partition_name
		,tablespace_name
		,extents
		,bytes
		,nvl(initial_extent,0) initial_extent
		,nvl(next_extent,0) next_extent
        from  dba_segments
       where  segment_name like '${NAME}%' 
	   order by 1,2,3,4;

BEGIN

        dbms_output.put_line(
		 substr('Tablespace Name'	||'                              ',1,20) ||' '||
		 substr('Owner'			||'                              ',1,10) ||' '||
		 substr('Segment Name'		||'                              ',1,26) ||' '||
		 substr('Partition Name'	||'                              ',1,30) ||' '||
		 substr('Seg Type'		||'                              ',1,5 ) ||' '||
		 substr('Init (KB)'		||'                              ',1,10) ||' '||
		 substr('Next (KB)'		||'                              ',1,10) ||' '||
		 substr('# Ext'		        ||'                              ',1,6)  ||' '||
		 substr('Alloc MB'		||'                              ',1,8)  ||' '||
		 substr('Used MB'		||'                              ',1,8) 
		 );

        dbms_output.put_line(
		lpad(' ',1+20,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+26,'=') ||
		lpad(' ',1+30,'=') ||
		lpad(' ',1+5,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+6,'=') ||
		lpad(' ',1+8,'=') ||
		lpad(' ',1+8,'=')
		 );
							 
    for obj in obj_cur loop
	
	if obj.segment_type='TEMPORARY'
	then
		v_total_bytes:=obj.bytes;
		v_unused_bytes:=0;
	else
	        dbms_space.unused_space(
			obj.owner
			,obj.segment_name  
			,obj.segment_type           
			,v_total_blocks              
			,v_total_bytes              
			,v_unused_blocks           
			,v_unused_bytes             
			,v_last_used_extent_file_id 
			,v_last_used_extent_block_id
			,v_last_used_block         
			,obj.partition_name                    );
	end if;

        dbms_output.put_line(
		substr(obj.tablespace_name	||'                              ',1,20) ||' '||
		substr(obj.owner		||'                              ',1,10) ||' '||
		substr(obj.segment_name		||'                              ',1,26) ||' '||
		substr(obj.partition_name	||'                              ',1,30) ||' '||
		substr(obj.segment_type		||'                              ',1,5 ) ||' '||
		to_char(obj.initial_extent/1024		,'9,999,999')  || ' ' ||
		to_char(obj.next_extent/1024		,'9,999,999')  || ' ' ||
		to_char(obj.extents			,'9,999')  || ' ' ||
		to_char(v_total_bytes/1024/1024		,'999,999')  || ' ' ||
		to_char((v_total_bytes-v_unused_bytes)/1024/1024  ,'999,999') 
	 );
    end loop;    

	dbms_output.put_line(
		lpad(' ',1+20,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+26,'=') ||
		lpad(' ',1+30,'=') ||
		lpad(' ',1+5,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+10,'=') ||
		lpad(' ',1+6,'=') ||
		lpad(' ',1+8,'=') ||
		lpad(' ',1+8,'=')
		 );

END;
/
EOF