#!/bin/sh
#*****************************************************************************
#
#  This script is used to show Redo Logs
#
#  USAGE: showredos
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************
sqlplus -s "/ as sysdba" <<EOF
set feed off
set lines 180 trimsp on 
col sequence_owner for a30
col sequence_name for a30
col percent_80 format 9,999,999,999,999
col min_value format 9,999,999,999,999
col max_value format 9,999,999,999,999
col last_number format 9,999,999,999,999
col perc for 999
select 
    sequence_owner, 
    sequence_name, 
    min_value, 
    max_value, 
    last_number, 
    trunc((max_value-min_value)*0.8+min_value) as percent_80,
    trunc((last_number-min_value)/(max_value-min_value)*100) perc
from dba_sequences 
where 
    sequence_owner not in ('SYSTEM','SYS','INDEPTH_AGENT','QCO','TOAD') and
    max_value-last_number < 20000000 and 
    trunc((last_number-min_value)/(max_value-min_value)*100) > 80;
EOF

