#!/bin/sh
#*****************************************************************************
#
#  This script is used to show Redo Logs
#
#  USAGE: showredos
#
#  By Adi Zohar - Feb 2003
#*****************************************************************************
sqlplus -s "/ as sysdba" <<EOF
set feed off pages 100
set lines 150
col bytes format 9,999,999,999,999
col member format a80
col FIRST_CHANGE# for 9,999,999,999,999,999
col status for a16

select group#,thread#,sequence#,members,bytes,archived,status ,FIRST_CHANGE#,to_char(first_time,'DD/MM/YYYY HH24:MI') first_time
from v\$log order by 1,2;

select group#, thread#, bytes, archived, status 
from V\$STANDBY_LOG order by 1,2;

select * from v\$logfile order by group#,member;
EOF

