SELECT COLUMN_NAME,
       SUM(ROW_COUNT) OVER (PARTITION BY PROJECTION_NAME, COLUMN_NAME) AS ROWS,
       USED_BYTES AS BYTES,
       ROUND(USED_BYTES::FLOAT / ROW_COUNT::FLOAT, 3) AS PER_ROW,
       ENCODINGS,
       COMPRESSIONS AS COMP,
       PROJECTION_NAME AS PROJECTION,
ANCHOR_TABLE_NAME AS TABLE,
       ROUND(SUM(USED_BYTES) OVER (PARTITION BY PROJECTION_NAME)::FLOAT / (1024 * 1024)::FLOAT, 2) AS MB
FROM COLUMN_STORAGE
WHERE ANCHOR_TABLE_NAME IN ('PRODUCT', 'SALES', 'STORE')
ORDER BY 9, 3 DESC, 4 DESC;